---

- name: 'configure pihole-vpn'
  become: true
  block:
  - name: 'get latest dns config checksum'
    delegate_to: '127.0.0.1'
    uri:
      url: '{{ pihole_vpn_conf_api_url }}'
      method: 'HEAD'
    register: 'vpn_dns_checksum'
  - name: 'get local dns config checksum'
    stat:
      path: '{{ configs.docker.scripts_path }}/02-vpn.conf'
      checksum_algorithm: 'sha256'
    register: 'local_vpn_dns_checksum'
    changed_when: 'local_vpn_dns_checksum.stat.checksum is not defined or local_vpn_dns_checksum.stat.checksum != vpn_dns_checksum.x_gitlab_content_sha256'

  - name: 'update vpn dns config'
    block:
    - name: 'create local temp file' # noqa command-instead-of-module
      become: false
      delegate_to: '127.0.0.1'
      command:
        cmd: 'mktemp'
      register: 'vpn_dns_temp'
    - name: 'download latest vpn dns config'
      become: false
      delegate_to: '127.0.0.1'
      get_url:
        url: '{{ pihole_vpn_conf_url }}'
        dest: '{{ vpn_dns_temp.stdout }}'
    - name: 'upload latest dns config'
      copy:
        src: '{{ vpn_dns_temp.stdout }}'
        dest: '{{ configs.docker.scripts_path }}/02-vpn.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
    - name: 'delete temp file'
      become: false
      delegate_to: '127.0.0.1'
      file:
        path: '{{ vpn_dns_temp.stdout }}'
        state: 'absent'
    - name: 'restart dns'
      command: '{{ configs.docker.scripts_path }}/hup.sh dns'
      ignore_errors: true
    when: 'local_vpn_dns_checksum.changed'
