---

- name: 'configure pihole-vpn'
  become: true
  block:
  - name: 'deploy dns entries for vpn'
    copy:
      src: '02-vpn.conf'
      dest: '{{ configs.docker.scripts_path }}/02-vpn.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    register: 'dns_update'

  - name: 'restart dns'
    command: '{{ configs.docker.scripts_path }}/hup.sh dns'
    ignore_errors: true
    when: 'dns_update.changed'
