version: 0.1
log:
  level: info
  formatter: text
http:
  addr: 0.0.0.0:5000
  host: docker.cr.imson.co
  secret: ###REPLACEME###
  headers:
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
