---

- name: 'configure pihole-lan'
  become: true
  block:
  - name: 'create lighttpd service config dir'
    file:
      state: 'directory'
      path: '/etc/systemd/system/lighttpd.service.d'
      owner: 'root'
      group: 'root'
      mode: '0755'

  - name: 'deploy lighttpd config to set cors configuration'
    copy:
      src: 'lighttpd.environ.conf'
      dest: '/etc/systemd/system/lighttpd.service.d/environ.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'

  - name: 'get latest dns config checksum'
    delegate_to: '127.0.0.1'
    uri:
      url: '{{ pihole_lan_conf_api_url }}'
      method: 'HEAD'
    register: 'lan_dns_checksum'
  - name: 'get local dns config checksum'
    stat:
      path: '/etc/dnsmasq.d/02-lan.conf'
      checksum_algorithm: 'sha256'
    register: 'local_lan_dns_checksum'
    changed_when: 'local_lan_dns_checksum.stat.checksum is not defined or local_lan_dns_checksum.stat.checksum != lan_dns_checksum.x_gitlab_content_sha256'

  - name: 'update lan dns config'
    block:
    - name: 'create local temp file' # noqa command-instead-of-shell
      become: false
      delegate_to: '127.0.0.1'
      command:
        cmd: 'mktemp'
      register: 'lan_dns_temp'
    - name: 'download latest lan dns config'
      become: false
      delegate_to: '127.0.0.1'
      get_url:
        url: '{{ pihole_lan_conf_url }}'
        dest: '{{ lan_dns_temp.stdout }}'
    - name: 'upload latest dns config'
      copy:
        src: '{{ lan_dns_temp.stdout }}'
        dest: '/etc/dnsmasq.d/02-lan.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
    - name: 'delete temp file'
      become: false
      delegate_to: '127.0.0.1'
      file:
        path: '{{ lan_dns_temp.stdout }}'
        state: 'absent'
    - name: 'restart dns'
      command: 'pihole restartdns'
    when: 'local_lan_dns_checksum.changed'
