---

- name: 'load and deploy host config'
  block:
  - name: 'create local temp file for config'
    become: false
    delegate_to: '127.0.0.1'
    command:
      cmd: 'mktemp' # noqa command-instead-of-module
    register: 'config_temp'
  - name: 'download config file for ansible host'
    become: false
    delegate_to: '127.0.0.1'
    get_url:
      url: 'https://gitlab.cr.imson.co/cr.imson.co/configs/-/raw/main/ansible/{{ ansible_hostname }}.conf.json'
      dest: '{{ config_temp.stdout }}'
  - name: 'slurp config file'
    become: false
    delegate_to: '127.0.0.1'
    slurp:
      src: '{{ config_temp.stdout }}'
    register: 'imported_config'
  - name: 'load config from slurped json'
    become: false
    set_fact:
      configs: '{{ imported_config.content | b64decode | from_json }}'
  - name: 'manage remote config directory'
    become: true
    file:
      state: 'directory'
      path: '{{ configs.homelab.config_path }}'
      owner: 'root'
      group: 'root'
      mode: '0755'
  - name: 'deploy configs.json'
    become: true
    copy:
      src: '{{ config_temp.stdout }}'
      dest: '{{ configs.homelab.config_path }}/configs.json'
      owner: 'root'
      group: 'root'
      mode: '0755'
  - name: 'delete local temp file'
    become: false
    delegate_to: '127.0.0.1'
    file:
      path: '{{ config_temp.stdout }}'
      state: 'absent'

- name: 'handle system automation config files'
  become: true
  block:
  - name: 'build configuration files'
    include_tasks: 'config_file.yml'
    loop: '{{ configs.global.config_list }}'
  - name: 'check for local secrets file'
    become: false
    delegate_to: '127.0.0.1'
    stat:
      path: 'secrets/{{ ansible_hostname }}.secrets.json'
    register: 'local_homelab_secrets'
  - name: 'deploy secrets file'
    copy:
      src: 'secrets/{{ ansible_hostname }}.secrets.json'
      dest: '{{ configs.homelab.config_path }}/secrets.json'
      owner: 'root'
      group: 'root'
      mode: '0700'
    when: 'local_homelab_secrets.stat.exists'
  - name: 'check for secrets file presence'
    stat:
      path: '{{ configs.homelab.config_path }}/secrets.json'
    register: 'homelab_secrets'
  - name: 'build secrets configuration file'
    block:
    - name: 'slurp secrets file'
      slurp:
        src: '{{ configs.homelab.config_path }}/secrets.json'
      register: 'imported_secrets'
    - name: 'load secrets file'
      set_fact:
        secrets: '{{ imported_secrets.content | b64decode | from_json }}'
    - name: 'create secrets file'
      template:
        src: 'secrets_config.sh.j2'
        dest: '{{ configs.homelab.config_path }}/secrets_config.sh'
        owner: 'root'
        group: 'root'
        mode: '0700'
    when: 'homelab_secrets.stat.exists'
