---
# common configuration playbook

- name: 'handle common configuration'
  become: true
  block:
  - name: 'update package cache'
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600

  - name: 'install common dependencies'
    apt:
      install_recommends: false
      name:
      - 'git'
      - 'htop'
      - 'zsh'
      - 'stow'
      - 'zip'
      - 'unzip'
      - 'tar'
      - 'curl'
      state: 'present'

  # todo: remove!
  #! this is temporary
  #    we need to reimage the rpi with the latest raspios, rebuild the dns server
  #    but for the time being we'll handle this problem with the tried and true method; ignoring it
  - name: 'install python 3.9'
    apt:
      install_recommends: false
      name:
      - 'python3.9'
    when: 'ansible_hostname != "rpi.cr.imson.co"'

  - name: 'install microcode package'
    block:
    - name: 'Add the debian nonfree repository'
      apt_repository:
        repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release | lower }} main contrib non-free'
        state: 'present'
      register: 'debian_nonfree_repo'
    - name: 'update package cache for new nonfree repo'
      apt:
        update_cache: true
        force_apt_get: true
      when: 'debian_nonfree_repo.changed'
    - name: 'install intel microcode package'
      apt:
        install_recommends: false
        name:
        - 'intel-microcode'
        state: 'present'
      when: '"Intel" in ansible_processor[1]'
    - name: 'install amd microcode package'
      apt:
        install_recommends: false
        name:
        - 'amd64-microcode'
        state: 'present'
      when: '"AMD" in ansible_processor[1]'
    when: 'ansible_distribution == "Debian" and ansible_architecture == "x86_64"'
