---

- name: 'manage volume-backup service'
  become: true
  block:
  - name: 'deploy volume-backup staging directory'
    file:
      state: 'directory'
      path: '{{ configs.backup.staging_path }}'
      owner: 'root'
      group: 'root'
      mode: '0770'

  - name: 'deploy volume-backup script'
    copy:
      src: 'volume-backup.sh'
      dest: '{{ configs.global.local_bin_path }}/volume-backup.sh'
      owner: 'root'
      group: 'staff'
      mode: '0744'

  - name: 'deploy volume-backup systemd service'
    copy:
      src: 'volume-backup.service'
      dest: '{{ configs.global.systemd_unit_path }}/volume-backup.service'
      owner: 'root'
      group: 'root'
      mode: '0644'
    register: 'volume_backup_service'

  - name: 'deploy volume-backup systemd timer'
    copy:
      src: 'volume-backup.timer'
      dest: '{{ configs.global.systemd_unit_path }}/volume-backup.timer'
      owner: 'root'
      group: 'root'
      mode: '0644'
    register: 'volume_backup_timer'

  - name: 'deploy volume-backup systemd timer system-level configuration directory'
    file:
      state: 'directory'
      path: '{{ configs.global.systemd_unit_path }}/volume-backup.timer.d'
      owner: 'root'
      group: 'root'
      mode: '0775'

  - name: 'deploy volume-backup systemd timer system-level configuration file'
    template:
      src: '01-volume-backup-schedule.conf.j2'
      dest: '{{ configs.global.systemd_unit_path }}/volume-backup.timer.d/01-volume-backup-schedule.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    register: 'volume_backup_timer_sched'

  - name: 'systemd daemon-reload'
    systemd:
      daemon_reload: true
    when: 'volume_backup_service.changed or volume_backup_timer.changed or volume_backup_timer_sched.changed'

  - name: 'deploy docker hook directories'
    file:
      state: 'directory'
      path: '{{ configs.docker.hook_path }}/{{ item }}'
      owner: 'root'
      group: 'docker'
      mode: '0770'
    with_items:
    - 'pre-backup'
    - 'post-backup'
    - 'snapshot-backup'
    - 'cleanup-backup'
    - 'move-backup'
    - 'backup-volume'
    - 'backup-image'

- name: 'manage volume-backup hooks'
  become: true
  copy:
    src: 'hooks/{{ item }}'
    dest: '{{ configs.docker.hook_path }}/{{ item }}'
    owner: 'root'
    group: 'docker'
    mode: '0770'
  with_items:
  - 'pre-backup/check-backup-mount.sh'
  - 'post-backup/notify-success.sh'
  - 'snapshot-backup/backup-repo.sh'
