#
# redbooru.io
#
# redbooru.io CI/CD environment docker configuration
# @author Damian Bushong <katana@odios.us>
#

version: "3.7"

networks:
  redbooru:
    name: redbooru
  crimson:
    name: crimson
    external: true

volumes:
  redbooru_db_data:
  redbooru_api_logs:
  redbooru_api_temp:
  redbooru_api_uploads:

secrets:
  mysql_root_password:
    file: ./mysql_root_password
  mysql_password:
    file: ./mysql_password

services:
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros:latest
    command: --labels-only --label-enable --interval 60
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  #
  # No UI images yet.
  # Disabled for now.
  #

  # ui:
  #   container_name: redbooru-ui
  #   image: docker.cr.imson.co/redbooru/ui
  #   restart: always
  #   hostname: redbooru.io
  #   environment:
  #     VIRTUAL_HOST: redbooru.io
  #     CERT_NAME: redbooru.io
  #     SSL_POLICY: Mozilla-Modern
  #     HTTPS_METHOD: redirect
  #   networks:
  #     redbooru:
  #       aliases:
  #         - ui
  #     crimson:
  #   ports:
  #     - "80"
  #   labels:
  #     - com.ouroboros.enable=true

  images:
    container_name: redbooru-images
    image: nginx:alpine
    restart: always
    hostname: i.redbooru.io
    environment:
      VIRTUAL_HOST: i.redbooru.io
      CERT_NAME: i.redbooru.io
      SSL_POLICY: Mozilla-Modern
      HTTPS_METHOD: redirect
    networks:
      redbooru:
        aliases:
          - images
      crimson:
    ports:
      - "80"
    volumes:
      - type: volume
        source: redbooru_api_uploads
        target: /usr/share/nginx/html/u
        read_only: true
    depends_on:
      - api

  api:
    container_name: redbooru-api
    image: docker.cr.imson.co/redbooru/api
    restart: always
    hostname: api.redbooru.io
    environment:
      VIRTUAL_PORT: "3000"
      VIRTUAL_HOST: api.redbooru.io
      CERT_NAME: api.redbooru.io
      SSL_POLICY: Mozilla-Modern
      HTTPS_METHOD: redirect
    networks:
      redbooru:
        aliases:
          - api
      crimson:
    ports:
      - "3000"
    volumes:
      - type: volume
        source: redbooru_api_logs
        target: /srv/redbooru/logs/
      - type: volume
        source: redbooru_api_temp
        target: /srv/redbooru/temp/
      - type: volume
        source: redbooru_api_uploads
        target: /srv/redbooru/upload/
      - type: bind
        source: /srv/redbooru/config/production.json
        target: /srv/redbooru/config/production.json
        read_only: true
    labels:
      - com.ouroboros.enable=true

  mariadb:
    container_name: redbooru-db
    image: mariadb:10.2
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: redbooru
      MYSQL_USER: redbooru
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    networks:
      redbooru:
        aliases:
          - redbooru-db
    ports:
      - "0.0.0.0:3333:3306"
    volumes:
      - type: volume
        source: redbooru_db_data
        target: /var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
