---
# package management playbook

- name: 'handle package management & updates'
  become: true
  block:
  - name: 'update package cache'
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600

  - name: 'update packages'
    apt:
      upgrade: 'dist'
      force_apt_get: true
