---

- name: 'manage and install docker-ce'
  become: true
  block:
  - name: 'install docker-ce dependencies'
    apt:
      install_recommends: false
      name:
      - 'acl'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg'
      - 'lsb-release'
      - 'python3-apt' # required for ansible apt_repository call
      state: 'present'

  - name: 'Remove docker apt signing key from main keyring'
    apt_key:
      id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
      state: 'absent'

  - name: 'Remove generic docker repository entry'
    apt_repository:
      filename: 'docker'
      repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable'
      state: 'absent'

  - name: 'Add the docker apt signing key'
    apt_key:
      url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
      state: 'present'
      keyring: '/usr/share/keyrings/docker-archive-keyring.gpg'

  - name: 'Add the docker repository'
    apt_repository:
      filename: 'docker'
      repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable'
      state: 'present'

  - name: 'install docker-ce dependencies'
    apt:
      install_recommends: false
      name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-compose-plugin'
      state: 'present'

  - name: 'install docker-compose v1'
    get_url:
      url: 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
      dest: '{{ configs.global.local_bin_path }}/docker-compose'
      checksum: 'sha256:f3f10cf3dbb8107e9ba2ea5f23c1d2159ff7321d16f0a23051d68d8e2547b323'
      owner: 'root'
      group: 'staff'
      mode: '0755'


