#!/usr/bin/env ansible-playbook
---

- hosts: 'aws'
  roles:
  - 'config'
  - 'common'
  - 'disable-init-user'
  - 'updates'
  - 'ssh'
  - 'ansible'
  - 'admin'
  - 'docker'
  - 'docker-stack'

- hosts: 'comet.cr.imson.co'
  roles:
  - 'certpackage'
  - 'docker-nginx'

- hosts: 'stellar.cr.imson.co'
  roles:
  - 'pihole-vpn'
