#!/usr/bin/env ansible-playbook
---

- hosts: 'all'
  roles:
  - 'common'
  - 'updates'
  - 'ssh'
  - 'ansible'
  - 'admin'

- hosts: 'homelab'
  roles:
  - 'config'
  - 'certsync'
  - 'docker'
  - 'docker-stack'
  - 'docker-nginx'
  - 'homelab-share-backup'
  - 'homelab-notifications'
  - 'homelab-landing-page'
  - 'mount-check'
  - 'mount-space-alert'
  - 'volume-backup'

- hosts: 'nomad.cr.imson.co'
  roles:
  - 'homelab-share-containers'
  - 'homelab-share-nextcloud'
  - 'homelab-share-registry'
  - 'homelab-reverse-proxy'
  - 'homelab-homer'

- hosts: 'aws'
  roles:
  - 'config'
  - 'disable-init-user'
  - 'docker'
  - 'docker-stack'

- hosts: 'rpi.cr.imson.co'
  roles:
  - 'pihole-lan'

- hosts: 'comet.cr.imson.co'
  roles:
  - 'certpackage'
  - 'docker-nginx'

- hosts: 'stellar.cr.imson.co'
  roles:
  - 'pihole-vpn'
