#!/usr/bin/env ansible-playbook
---

- hosts: 'nomad.cr.imson.co'
  roles:
  - 'config'
  - 'certsync'
  - 'homelab-share-backup'
  - 'homelab-share-containers'
  - 'homelab-share-nextcloud'
  - 'homelab-share-registry'
  - 'docker'
  - 'docker-stack'
  - 'docker-nginx'
  - 'homelab-notifications'
  - 'homelab-landing-page'
  - 'homelab-reverse-proxy'
  - 'homelab-homer'
  - 'mount-check'
  - 'mount-space-alert'
  - 'volume-backup'

- hosts: 'rpi.cr.imson.co'
  roles:
  # - 'config'
  - 'pihole-lan'
