# init:
#   hosts:
#     hostname.cr.imson.co:

docker_stack:
  hosts:
    stellar.cr.imson.co:
    comet.cr.imson.co:
    nomad.cr.imson.co:
    nemesis.cr.imson.co:

aws:
  hosts:
    stellar.cr.imson.co:
    comet.cr.imson.co:

homelab:
  hosts:
    nomad.cr.imson.co:
    nemesis.cr.imson.co:

dns:
  hosts:
    rpi.cr.imson.co:

pi:
  children:
    pi3:
      rpi.cr.imson.co:
    pi4:
      hosts:
        pi4-01.cr.imson.co:
        pi4-02.cr.imson.co:
        pi4-03.cr.imson.co:
        pi4-04.cr.imson.co:

k3s:
  children:
    k3s_master:
      hosts:
        pi4-01.cr.imson.co:
    k3s_workers:
      hosts:
        pi4-02.cr.imson.co:
        pi4-03.cr.imson.co:
        pi4-04.cr.imson.co:

wireguard:
  children:
    wireguard_server:
      stellar.odios.us:
    wireguard_clients:
      nomad.cr.imson.co:
      nemesis.cr.imson.co:
      comet.cr.imson.co:
      pi4-01.cr.imson.co:
      pi4-02.cr.imson.co:
      pi4-03.cr.imson.co:
      pi4-04.cr.imson.co:

all:
  vars:
    ansible_user: 'devoops'
    ansible_port: 4
    ansible_python_interpreter: '/usr/bin/python3'
    ansible_ssh_private_key_file: '~/.ssh/ansible'
