# init:
#   hosts:
#     hostname.cr.imson.co:

aws:
  hosts:
    # janus.cr.imson.co:
    stellar.cr.imson.co:
    comet.cr.imson.co:

homelab:
  hosts:
    nomad.cr.imson.co:
    nemesis.cr.imson.co:

dns:
  hosts:
    rpi.cr.imson.co:

# wireguard_server:
#   hosts:
#     # deliberate - separate dns entry needed if we have to bypass VPN
#     #   and directly connect to the server
#     stellar.odios.us:
#       vpn_endpoint: 'stellar.odios.us'
#       vpn_port: '51820'
#       vpn_network_cidr: '10.10.0.0/22'
#       vpn_dns_ip: '10.10.0.2'

# wireguard:
#   hosts:
#     nomad.cr.imson.co:
#       vpn_ip: '10.10.1.1'
#     comet.cr.imson.co:
#       vpn_ip: '10.10.0.2'
#     # janus.cr.imson.co:
#     #   vpn_ip: '10.10.0.3'
#     nemesis.cr.imson.co:
#       vpn_ip: '10.10.1.7'

all:
  vars:
    ansible_user: 'devoops'
    ansible_port: 4
    ansible_python_interpreter: '/usr/bin/python3'
    ansible_ssh_private_key_file: '~/.ssh/ansible'
