#!/usr/bin/env ansible-playbook
---

- hosts: 'all'
  vars:
    ansible_user: 'ubuntu'
    ansible_ssh_private_key_file: '~/.ssh/ec2-init-lumina'
    ansible_port: 22
  become: true
  roles:
  - 'init'
  - 'common'
  - 'updates'
  - 'ssh'
  - 'ansible'
  - 'admin'
