#!/usr/bin/env ansible-playbook
---

- hosts: 'wireguard'
  roles:
  - 'wireguard-ansible-config'

- hosts: 'wireguard_server'
  roles:
  - 'wireguard-server'

- hosts: 'wireguard_clients'
  roles:
  - 'wireguard-client'

- hosts: 'wireguard_server'
  roles:
  - 'wireguard-config'
