#
# cr.imson.co
#
# Home Lab docker configuration
# @author Damian Bushong <katana@odios.us>
#

version: '3.7'

networks:
  crimson:
    name: 'crimson'

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  nextcloud_root:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_data:
  nextcloud_mariadb_data:
  portainer_data:
  gitlab_runner_config:

secrets:
  nextcloud_mysql_root_password:
    file: './nextcloud_mysql_root_password'
  nextcloud_mysql_password:
    file: './nextcloud_mysql_password'
  portainer_admin_password:
    file: './portainer_admin_password'

services:
  nginx-proxy:
    container_name: 'nginx'
    image: 'nginxproxy/nginx-proxy:latest'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      DEFAULT_HOST: 'cr.imson.co'
    networks:
    - 'crimson'
    ports:
    - '0.0.0.0:80:80'
    - '0.0.0.0:443:443'
    volumes:
    - type: 'bind'
      source: '/var/run/docker.sock'
      target: '/tmp/docker.sock'
      read_only: true
    - type: 'bind'
      source: '/etc/nginx/certs'
      target: '/etc/nginx/certs'
      read_only: true
    - type: 'bind'
      source: '/etc/nginx/vhost.d'
      target: '/etc/nginx/vhost.d'
      read_only: true
    healthcheck:
      test: 'service nginx status >/dev/null || exit 1'
      start_period: '1m'
      interval: '3m'
      retries: 3

  nginx:
    container_name: 'landing_page'
    image: 'nginx:alpine'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_HOST: 'cr.imson.co'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
    networks:
      crimson:
    volumes:
    - type: 'bind'
      source: '/srv/html'
      target: '/usr/share/nginx/html'
      read_only: true
    healthcheck:
      test: 'curl -IsSLf http://localhost/ >/dev/null || exit 1'
      start_period: '1m'
      interval: '3m'
      retries: 3

  homelab_proxy:
    container_name: 'homelab_proxy'
    image: 'nginx:alpine'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_HOST: 'nas.cr.imson.co,network.cr.imson.co,dns.cr.imson.co'
      VIRTUAL_PORT: '80'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
    networks:
      crimson:
    volumes:
    - type: 'bind'
      source: '/srv/proxy'
      target: '/etc/nginx/conf.d'
      read_only: true
    # healthcheck:
    #   test: 'curl -IsSLf http://localhost/ >/dev/null || exit 1'
    #   start_period: '1m'
    #   interval: '3m'
    #   retries: 3

  homer:
    container_name: 'homer'
    image: 'b4bz/homer:latest'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_PORT: '8080'
      VIRTUAL_HOST: 'hub.cr.imson.co'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
      INIT_ASSETS: 0
    networks:
      crimson:
    volumes:
    - type: 'bind'
      source: '/srv/homer'
      target: '/www/assets'
      read_only: true
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1'
      start_period: '1m'
      interval: '3m'
      retries: 3

  gitlab:
    container_name: 'gitlab'
    image: 'gitlab/gitlab-ce:latest'
    restart: 'unless-stopped'
    stop_grace_period: '2m'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_HOST: 'gitlab.cr.imson.co,containers.cr.imson.co'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
      GITLAB_OMNIBUS_CONFIG: 'from_file("/gitlab_config.rb")'
    networks:
      crimson:
        aliases:
        - 'gitlab'
        - 'containers'
    ports:
    # gitlab needs to be the only one on port 22
    # if this isn't the case, change the left port to match
    #   the gitlab_rails['gitlab_shell_ssh_port'] configuration directive
    - '0.0.0.0:22:22'
    volumes:
    - type: 'volume'
      source: 'gitlab_config'
      target: '/etc/gitlab'
    - type: 'volume'
      source: 'gitlab_logs'
      target: '/var/log/gitlab'
    - type: 'volume'
      source: 'gitlab_data'
      target: '/var/opt/gitlab'
    - type: 'bind'
      source: '/mnt/registry'
      target: '/mnt/registry'
    - type: 'bind'
      source: '/mnt/containers'
      target: '/mnt/containers'
    - type: 'bind'
      source: '/srv/docker/gitlab_config.rb'
      target: '/gitlab_config.rb'
      read_only: true

  nextcloud_app:
    container_name: 'nextcloud_app'
    image: 'containers.cr.imson.co/cr.imson.co/nextcloud-custom:24-fpm'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: 'cloud.cr.imson.co'
      NEXTCLOUD_OVERWRITEPROTOCOL: 'https'
      MYSQL_HOST: 'nextcloud-db'
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_PASSWORD_FILE: '/run/secrets/nextcloud_mysql_password'
    networks:
      crimson:
        aliases:
        - 'nextcloud-app'
    volumes:
    - type: 'volume'
      source: 'nextcloud_root'
      target: '/var/www/html'
    - type: 'volume'
      source: 'nextcloud_apps'
      target: '/var/www/html/custom_apps'
    - type: 'volume'
      source: 'nextcloud_config'
      target: '/var/www/html/config'
    - type: 'bind'
      source: '/mnt/nextcloud'
      target: '/var/www/html/data'
    - type: 'volume'
      source: 'nextcloud_data'
      target: '/mnt/data'
    secrets:
    - 'nextcloud_mysql_password'
    depends_on:
    - 'nextcloud_db'

  nextcloud_db:
    container_name: 'nextcloud_db'
    image: 'mariadb:10.7'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    command: >
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --skip-innodb-read-only-compressed
      --innodb-file-per-table=1
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/nextcloud_mysql_root_password'
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_PASSWORD_FILE: '/run/secrets/nextcloud_mysql_password'
    networks:
      crimson:
        aliases:
          - 'nextcloud-db'
    volumes:
    - type: 'volume'
      source: 'nextcloud_mariadb_data'
      target: '/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping --silent'
      start_period: '1m'
      interval: '3m'
      retries: 3
    secrets:
    - 'nextcloud_mysql_root_password'
    - 'nextcloud_mysql_password'

  nextcloud_nginx_translator:
    container_name: 'nextcloud_nginx'
    image: 'containers.cr.imson.co/cr.imson.co/nextcloud-nginx-translator:latest'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_HOST: 'cloud.cr.imson.co'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
    networks:
      crimson:
        aliases:
          - 'cloud'
    volumes:
    - type: 'volume'
      source: 'nextcloud_root'
      target: '/var/www/html'
      read_only: true
    healthcheck:
      test: 'curl -IsLf http://localhost/login >/dev/null || exit 1'
      start_period: '1m'
      interval: '3m'
      retries: 3
    depends_on:
    - 'nextcloud_app'

  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce:2.13.1'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    environment:
      VIRTUAL_PORT: '9000'
      VIRTUAL_HOST: 'portainer.cr.imson.co'
      CERT_NAME: 'cr.imson.co'
      SSL_POLICY: 'Mozilla-Intermediate'
      HTTPS_METHOD: 'redirect'
    networks:
      crimson:
        aliases:
        - 'portainer'
    ports:
    - '0.0.0.0:8000:8000'
    volumes:
    - type: 'volume'
      source: 'portainer_data'
      target: '/data'
    - type: 'bind'
      source: '/var/run/docker.sock'
      target: '/var/run/docker.sock'
    secrets:
    - 'portainer_admin_password'

  runner:
    container_name: 'gitlab_runner'
    image: 'gitlab/gitlab-runner:latest'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '10m'
    networks:
      crimson:
    # healthcheck:
    #   test: 'curl -IsLf http://localhost/login >/dev/null || exit 1'
    #   start_period: '1m'
    #   interval: '3m'
    #   retries: 3
    volumes:
    - type: 'volume'
      source: 'gitlab_runner_config'
      target: '/etc/gitlab-runner'
    - type: 'bind'
      source: '/var/run/docker.sock'
      target: '/var/run/docker.sock'
    depends_on:
    - 'gitlab'
