version: '3.8'

networks:
  underworld:
    name: 'underworld'

services:
  placeholder:
    container_name: 'placeholder'
    image: 'alpine:3.8'
    restart: 'unless-stopped'
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: '1m'
    networks:
      underworld:
    command: 'sh -c "while true; do sleep 30; done;"'
